---
title: "QuantCrit in Undergraduate Mathematics General Education"
always_allow_html: true
output:
  word_document: 
    fig_caption: true
  pdf_document:
    toc: false
    toc_depth: 2
    number_section: true 
  html_document:
    toc: true
    toc_depth: 2
    number_sections: true
    theme: flatly
geometry: margin=1.0in
editor_options:
  markdown:
    wrap: sentence
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, # By default, hide code; set to TRUE to see code
  fig.pos = 'th', # Places figures at top or here
  out.width = '100%', dpi = 300, # Figure resolution and size
  fig.env="figure"
) # Latex figure environment

# install.packages("bibliometrix")
library(bibliometrix)

layout="l-body-outset"
library(rmarkdown)

options(knitr.table.format = "latex") # For kable tables to write LaTeX table directly
```

```{r, include=F, warning=F}
## set up, load libraries
library(dplyr)
library(readtext)
library(tidyverse)
library(here)
library(gt)
library(ggplot2)
library(dplyr)
library(knitr)
library(kableExtra)
here::i_am("quant-crit-math.Rmd")
```
